name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Setup Directories
      run: mkdir deployment

    - name: Build (linux/arm64)
      run: GOOS=linux GOARCH=arm64 make build && cp bin/wosu deployment/wosu-linux-arm64
      
    - name: Build (linux/amd64)
      run: GOOS=linux GOARCH=amd64 make build && cp bin/wosu deployment/wosu-linux-amd64
  
