name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true

    - name: Install Dependencies
      run: go get .

    - name: Setup Directories
      run: mkdir deployment

    - name: Build (linux/arm64)
      run: GOOS=linux GOARCH=arm64 make build && cp bin/wosu deployment/wosu-linux-arm64
      
    - name: Build (linux/amd64)
      run: GOOS=linux GOARCH=amd64 make build && cp bin/wosu deployment/wosu-linux-amd64
      
    - name: Build (macOS/arm64)
      run: GOOS=darwin GOARCH=arm64 make build && cp bin/wosu deployment/wosu-macos-arm64
      
    - name: Build (macOS/amd64)
      run: GOOS=darwin GOARCH=amd64 make build && cp bin/wosu deployment/wosu-macos-amd64
  
    - name: Build (windows/arm64)
      run: GOOS=windows GOARCH=arm64 make build && cp bin/wosu.exe deployment/wosu-windows-arm64.exe
      
    - name: Build (windows/amd64)
      run: GOOS=windows GOARCH=amd64 make build && cp bin/wosu.exe deployment/wosu-windows-amd64.exe
  
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          deployment/wosu-linux-arm64
          deployment/wosu-linux-amd64
          deployment/wosu-macos-arm64
          deployment/wosu-macos-amd64
          deployment/wosu-windows-arm64.exe
          deployment/wosu-windows-amd64.exe
